export type LocaleKey = "en-IN"

export const STRINGS: Record<LocaleKey, Record<string, string>> = {
  "en-IN": {
    app_title: "Village Insurance",
    dashboard_title: "Dashboard",
    dao_console: "DAO Console",
    policies: "Policies",
    policy_editor: "Policy Editor",
    profile: "Profile",
    investor: "Investor Dashboard",
    admin_audit: "Admin Audit Trail",
    dev_panel: "Dev Control Panel",
    pool_total: "Total Pool",
    yield_rate: "Yield Rate",
    available_to_withdraw: "Available to Withdraw",
    pending_votes: "Pending DAO Votes",
    my_subscriptions: "My Subscriptions",
    investor_snapshot: "Investor Snapshot",
    subscribe: "Subscribe",
    archive: "Archived",
    active: "Active",
    pending: "Pending",
    deleted: "Deleted",
    vote_yes: "Vote Yes",
    vote_no: "Vote No",
    voting_ends: "Voting ends",
    in_label: "in",
    create_policy: "Create Policy",
    policy_title: "Policy Title",
    description: "Description",
    premium_amount: "Premium Amount",
    currency: "Currency",
    max_claim: "Max Claim",
    interest_rate: "Interest Rate (bps)",
    claim_cooldown: "Claim Cooldown (days)",
    investor_lockin: "Investor Lock-in (days)",
    requires_dao_approval: "Requires DAO Approval",
    credit_slash: "Credit Slash on Reject",
    submit: "Submit",
    cancel: "Cancel",
    subscribe_to_policy: "Subscribe to Policy",
    step_review: "Step 1: Review",
    step_pay: "Step 2: Pay First Premium",
    step_done: "Step 3: Confirmed",
    connect_wallet: "Connect Wallet",
    pay_premium: "Pay Premium",
    start_date: "Start Date",
    claim_new: "New Claim",
    upload_image: "Upload Image",
    amount: "Amount",
    claim_description: "Claim Description",
    file_alt: "Uploaded claim image",
    submit_claim: "Submit Claim",
    claim_status: "Claim Status",
    vote_progress: "Vote Progress",
    credit_score: "Credit Score",
    banned: "Banned",
    deposit: "Deposit",
    withdraw: "Withdraw",
    locked_until: "Locked until",
    not_eligible_withdraw: "Not eligible to withdraw yet",
    transaction_status: "Transaction Status",
    success: "Success",
    failed: "Failed",
    refresh: "Refresh",
    timezone: "Timezone",
    view_local_time: "View in local time",
    asia_kolkata: "Asia/Kolkata",
    image_upload_failed: "Image upload failed",
    retry: "Retry",
    reason: "Reason",
    cooldown_blocks_claim: "Claim blocked until cooldown ends on",
    grace_forfeiture: "Subscription forfeited after grace period",
    double_spend_risk: "Conflict detected: potential double-spend",
    manual_refresh: "Manual Refresh",
    premium_due: "Premium Due",
    pay_now: "Pay Now",
    paid: "Paid",
    dao_only_action: "DAO-only action",
    member_mgmt: "Member Management",
    add_member: "Add Member",
    remove_member: "Remove Member",
    ban_user: "Ban User",
    proposals: "Proposals",
    create_proposal: "Create Proposal",
    audit_trail: "Audit Trail",
  },
}
